In [42]:
import logging
import threading
import time

def thread_function(name):
    logging.info("Thread %s: starting", name)
    time.sleep(2)
    logging.info("Thread %s: finishing", name)

if __name__ == "__main__":
    format = "%(asctime)s: %(message)s"
    logging.basicConfig(format=format, level=logging.INFO,
                        datefmt="%H:%M:%S")

    logging.info("Main    : before creating thread")
    x = threading.Thread(target=thread_function, args=(1,))
    logging.info("Main    : before running thread")
    x.start()
    logging.info("Main    : wait for the thread to finish")
    # x.join()
    logging.info("Main    : all done")


20:36:26: Main    : before creating thread
20:36:26: Main    : before running thread
20:36:26: Thread 1: starting
20:36:26: Main    : wait for the thread to finish
20:36:26: Main    : all done


In [43]:
import platform
platform.python_implementation()


'CPython'

In [44]:
d = make_bricks(7, 1, 13)
print (d)

NameError: name 'make_bricks' is not defined

In [45]:
def make_bricks(small, big, goal):
    s=

SyntaxError: invalid syntax (<ipython-input-45-1da95d27bc73>, line 2)

In [46]:
from operator import itemgetter
def house(plan):
    print(plan) 
    x=0
    y=[]
    for i in plan.split('\n'):
        x+=1
        if i.find('#')!=-1:
            
            y.append([x,i.find('#'),len(i)-(i[::-1].find('#'))-1])
    if y ==[]:
        return 0
    return (max(y,key=lambda x:x[2])[2]+1-min(y,key=lambda x:x[1])[1])*(max(y,key=lambda x:x[0])[0]+1-min(y,key=lambda x:x[0])[0])

if __name__ == '__main__':
    print("Example:")
    print(house('''
0000000
##00##0
######0
##00##0
#0000#0
    '''))

Example:

0000000
##00##0
######0
##00##0
#0000#0
    
24


In [47]:
FIRST_TEN = ["one ", "two ", "three ", "four ", "five ", "six ", "seven ",
             "eigh t", "nine "]
SECOND_TEN = ["ten ", "eleven ", "twelve ", "thirteen ", "fourteen ", "fifteen ",
              "sixteen ", "seventeen ", "eighteen ", "nineteen "]
OTHER_TENS = ["twenty ", "thirty ", "forty ", "fifty ", "sixty ", "seventy ",
              "eighty ", "ninety "]
HUNDRED = "hundred "

def checkio(number):
    if number > 100:
        return FIRST_TEN[number//100-1]+HUNDRED+
        
checkio(218)

SyntaxError: invalid syntax (<ipython-input-47-674e86e4948f>, line 11)

In [48]:
lis = [[1,'q','z'],[2,'w','x'],[1,'s','x'],[3,'q','z']]
a={}
for i in lis:
    a.setdefault(i[0], []).append(i[1])
print(a)
        


{1: ['q', 's'], 2: ['w'], 3: ['q']}


In [49]:
categories={'1':['11','12','13'],'11':['21','22','23'],'12':['31','32','33']}
test = {}
test1 = ['4','5','6']
_list=['11','12','13']
MLP={'Only Curators Can See This': ['curator voice chat', 'curator-chat'], 'None': ['Hi my friend', 'ONLY ADMIN Can See this', 'General chat', 'MLP Core .Net', 'VK Management', 'WEB Site Python', 'Discord Bot', 'Web Server', 'test them all', 'Only Curators Can See This'], 'Hi my friend': ['here-you-are', 'read-me-first', 'tell-about-your-goal'], 'ONLY ADMIN Can See this': ['log-discord-changes', 'log-user', 'passwords', 'amdin-chat'], 'General chat': ['start-info', 'discussion', 'suggestions', 'discussion-of-suggestions', 'book-of-complaints', 'daily-motivation', 'off-topic'], 'MLP Core .Net': ['info', 'classroom', 'tasks-core', 'step-by-step', 'questions', 'discussion', 'git-activity', 'git-activity-net'], 'VK Management': ['info', 'questions', 'discussion', 'think', 'git'], 'WEB Site Python': ['info', 'request-for-participation', 'step-by-step', 'questions', 'git-activity', 'discussion', 'tasks-backend'], 'Discord Bot': ['info', 'step-by-step', 'participation', 'discussion', 'task', 'git-activity'], 'Web Server': ['info', 'classroom', 'discussion', 'questions', 'requirements'], 'test them all': ['info', 'discussion', 'git-activity', 'questions', 'github-learning-lab', 'cool-links', 'noisy-tests', 'automaton']}
# d={}
# for indx,i in enumerate(categories['1']):
#     print(categories[i])
#     categories['string_'+str(indx)]=('\t'.join(map(str,categories[i])).title()  )


# test.setdefault('one',[]).append()
# print(test)

# def create_tree(name,obj):
#     for i in obj[name]:
#         yield name,list(create_tree(i,obj)) if i in obj else ''
print(MLP['None'])

['Hi my friend', 'ONLY ADMIN Can See this', 'General chat', 'MLP Core .Net', 'VK Management', 'WEB Site Python', 'Discord Bot', 'Web Server', 'test them all', 'Only Curators Can See This']


20:36:28: Thread 1: finishing


In [50]:
x = [1,2,3]
print(x.__hash__)

None


In [51]:
received=['___no','one','two']
for i in range(len(received)):
    print(received.pop() if received[-1]!='___no' else 'not')

two
one
not


In [52]:
import matplotlib.pyplot as plt
import numpy as np

# Fixing random state for reproducibility
np.random.seed(19680801)


x = np.arange(0.0, 50.0, 5.0)
y = x ** 1.3 + np.random.rand(*x.shape) * 30.0
s = np.random.rand(*x.shape) * 800 + 500

plt.scatter(x, y, s, c="r", alpha=0.2, marker=r'$\clubsuit$',
            label="Luck")
plt.xlabel("Leprechauns")
plt.ylabel("Gold")
plt.legend(loc='upper left')
plt.show()


In [53]:

def some_funct(a,arg=[]):
    return arg.append(a)
a='foo'
print( some_funct(a))

None


In [54]:
def foo(a,arg=[]):
    arg.append(a)
    return arg
print(foo('car'))
print(foo('ran'))

['car']
['car', 'ran']


In [55]:
a=1
b=1
a is b

True

In [56]:
b=300
c=300
b is c

False

In [58]:
class Mapping(Generic[KT, VT]):
    def __getitem__(self, key: KT) -> VT:
        pass

X = TypeVar('X')
Y = TypeVar('Y')

def lookup_name(mapping: Mapping[X, Y], key: X, default: Y) -> Y:
    try:
        return mapping[key]
    except KeyError:
        return default

NameError: name 'Generic' is not defined

In [59]:
class DiscordNode:
    def __init__(self, 
                aNodeName:str =None, 
                aNodeKind:str =None,
                aNodeDescr:str =None):
        self.NodeName = aNodeName
        self.NodeKind = aNodeKind
        self.NodeDescr = aNodeDescr
dn = DiscordNode("MLP Discord","root","Discord" )
print(DiscordNode.__init.__dict__)

AttributeError: type object 'DiscordNode' has no attribute '__init'

In [60]:
def squre(n,p):
    res=0
    for i in str(n):
        res+=int(i)**p
        print(f'{i}**{p} = ',int(i)**p)
        p+=1
    return res

In [61]:
squre(46288,3)

4**3 =  64
6**4 =  1296
2**5 =  32
8**6 =  262144
8**7 =  2097152


2360688

In [62]:
for x in range(0, 9):
    globals()['string%s' % x] = 'Hello'
    if x==8:
        globals()['string%s' % x]='Not Hello'
    print(globals()['string%s' % x])


Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Not Hello


In [63]:
print(300==300)
print(200==200)

True
True


In [64]:
arr=[2,6,4,8,4,2,443,5,7,8,9,7,6,54,6,3,234,45,678,]
def summ(arr):
    i,*els = arr
    return i+ summ(els) if els else 0
print(summ(arr))

853


In [65]:


def convert_base(num, to_base=10, from_base=10):
    # first convert to decimal number
    if isinstance(num, str):
        n = int(num, from_base)
    else:
        n = int(num)
    # now convert decimal to 'to_base' base
    alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    if n < to_base:
        return alphabet[n]
    else:
        return convert_base(n // to_base, to_base) + alphabet[n % to_base]

In [66]:
convert_base ('10',to_base=16,from_base=2)

'2'

In [67]:
n = int('1010', 2)
print(n)

10


In [68]:
medals ={':unranked:':'1' ,':bronze:':'10' ,':silver:':'100', 
        ':gold:':'1000', ':platinum:':'10000' ,':diamond:':'100000' ,
        ':master:' :'1000000',':devops:':'10000000' ,':scientist:':'100000000' }
print(int(medals[':bronze:'],4))


4


In [69]:
from itertools import repeat
x='str'
l = []
l.extend(repeat(x, 0))
print(l)

[]


In [70]:
def fmt_item(lines, max_lines=0):
    max_width = max([len(line) for line in lines])
    empty = ' '*max_width
    lines = [line.ljust(max_width) for line in lines]
    lines += [empty] * (max_lines - len(lines))
    return lines
def pp(*lst):
    lines = [str(item).split('\n') for item in lst]
    max_lines = max([len(item) for item in lines])
    lines = [fmt_item(item, max_lines=max_lines) for item in lines]
    lines_t = np.array(lines).T
    print('\n'.join([' '.join(line) for line in lines_t]))

In [71]:
from math import *
import numpy as np
x = (1,1)
y = (5,3)

ranges =np.fromiter([ i-j for i,j in zip(x,y)],np.int8)

dist=np.sum(np.abs(ranges))

print(dist)

6


In [72]:
def two_loop (A,B,R):
    for i in range(A.shape[0]):
        for j in range(B.shape[0]):
            ranges = A[i]-B[j]
            R[i,j] =  np.sum(np.abs(ranges))
            

In [73]:
def one_loop (A,B,R):
    for i in range(A.shape[0]):
        R[i]=np.sum(np.abs(B-A[i]),axis = 1)
        pp(np.sum(np.abs(B-A[i]),axis = 1))
       

In [74]:
def no_loop (A,B,R):
    R[:]=np.sum(np.abs(B-A[:,None]),axis = 2)[:]
#     pp(np.abs(B-A[:,None]))
    pp(A[:,None])

In [75]:
import numpy as np
np.random.seed(42)
A = np.random.randint(10,size=(3,5))
B = np.random.randint(10,size=(3,5))
R = np.zeros ((A.shape[0],B.shape[0]),np.float32)
#two_loop (A,B,R)
#one_loop(A,B,R)
no_loop(A,B,R)
#pp(A,B)
pp(A,'-',B, '=',R)

[[[6 3 7 4 6]] 
               
 [[9 2 6 7 4]] 
               
 [[3 7 7 2 5]]]
[[6 3 7 4 6]  - [[4 1 7 5 1]  = [[10. 10. 22.] 
 [9 2 6 7 4]     [4 0 9 5 8]     [12. 16. 22.] 
 [3 7 7 2 5]]    [0 9 2 6 3]]    [14. 16. 16.]]


In [76]:
test_A=np.arange(15).reshape(3,5)

In [77]:
pp(test_A[0].T,test_A[0:1].T,test_A[0].T-test_A[0:1].T)

[0 1 2 3 4] [[0]  [[ 0  1  2  3  4] 
             [1]   [-1  0  1  2  3] 
             [2]   [-2 -1  0  1  2] 
             [3]   [-3 -2 -1  0  1] 
             [4]]  [-4 -3 -2 -1  0]]


In [78]:
pp (B - test_A[:,None] )

[[[  4   0   5   2  -3]  
  [  4  -1   7   2   4]  
  [  0   8   0   3  -1]] 
                         
 [[ -1  -5   0  -3  -8]  
  [ -1  -6   2  -3  -1]  
  [ -5   3  -5  -2  -6]] 
                         
 [[ -6 -10  -5  -8 -13]  
  [ -6 -11  -3  -8  -6]  
  [-10  -2 -10  -7 -11]]]


In [79]:
print ( test_A[:,None] -B )

[[[-4  0 -5 -2  3]
  [-4  1 -7 -2 -4]
  [ 0 -8  0 -3  1]]

 [[ 1  5  0  3  8]
  [ 1  6 -2  3  1]
  [ 5 -3  5  2  6]]

 [[ 6 10  5  8 13]
  [ 6 11  3  8  6]
  [10  2 10  7 11]]]


In [80]:
from datetime import datetime,timedelta
delta = [timedelta (hours = i) for i in range(0,4)]
time = datetime.today().replace(second = 0,microsecond = 0)
times = [time+delt for delt in delta]
print(time , times)
if time in times:
    print ('it is')

2019-07-27 20:37:00 [datetime.datetime(2019, 7, 27, 20, 37), datetime.datetime(2019, 7, 27, 21, 37), datetime.datetime(2019, 7, 27, 22, 37), datetime.datetime(2019, 7, 27, 23, 37)]
it is


In [81]:
import numpy as np

actu = np.array([True,True,False,True,False,False])
pred = np.array([False,True,True,False,False,True])

TP = actu[pred == False]
print(TP[TP])

[ True  True]


In [82]:
bools = np.array([np.mean(i) for i in bols])>0.5
print(bools)


NameError: name 'bols' is not defined

In [83]:
for i in bols:
    bools = me(i)

NameError: name 'bols' is not defined

In [84]:
from datetime import datetime

In [85]:
t = datetime.today().minute
print(t)

37


In [86]:
lists_ = [np.random.choice(a = [True,False], size = 20) for i in range(5)]
print(lists_)

[array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False, False, False, False,  True, False,
        True, False]), array([False, False,  True, False,  True, False,  True, False,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False]), array([False, False, False,  True,  True, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
        True, False]), array([ True, False, False,  True, False,  True, False,  True,  True,
       False, False,  True, False, False, False,  True,  True,  True,
        True,  True]), array([ True,  True,  True,  True, False,  True, False, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False])]


In [87]:
import numpy as np# x is your dataset
x = np.arange(20)
x_split = np.split(x,5)
print(len(x_splitplit))

NameError: name 'x_splitplit' is not defined

In [88]:
def pred_func (list_):
    in_list = np.copy(list_)
    indxes = np.random.randint(0,20,2)
    indxes = [0,1]
    in_list[indxes] = ~in_list[indxes]
    return  in_list
    

In [89]:
def acurecy (gr_t,pred):
    return len(pred[gr_t == pred])/len(gr_t)

In [90]:
[acurecy(pred_func(list_),list_) for list_ in lists_ ]

[0.9, 0.9, 0.9, 0.9, 0.9]

In [91]:
print(pred_func(list_).shape)

NameError: name 'list_' is not defined

In [ ]:

import numpy as np
k_primes=[]

def count_Kprimes(k, start, nd):
    if start == 0:
        start =1
    k_numbers = []
    max_nd_prime = n_primes(int(nd/2)+1)
    for i in range(nd+1-start):
        if is_dev(i+start,max_nd_prime) == k:
            k_numbers.append(i+start)            
    return k_numbers
    
def is_k_prime(num,k,nd):
    global k_primes
    k_primes = []
    devide(num,nd) 
    if len(k_primes)==k:
        return True
    
        
def devide (num,rng):
    global k_primes
    for i in rng:
        if num%i == 0 :
            k_primes.append(i)
            return devide(num/i,rng) if num/i!= 1 else 1
        else:
            return 1
        
def is_dev(num,i):
    i1,*il=i    
    if num%i1==0:
        return 1+is_dev(num/i1,i) 
    else:
        return is_dev(num,il) if num>1 else 0
    
        
def n_primes (n):
    k_prime = np.ones((n),dtype = bool)
    for i in range(2,n):
        if k_prime[i] == True:
            for j in range(i*2,n,i):
                k_prime[j]=False
            
    return k_prime.nonzero()[0][2:].astype(np.int32)



In [ ]:
is_dev(12,n_primes (100))

In [92]:
%prun count_Kprimes(5, 500, 1000)

NameError: name 'count_Kprimes' is not defined

In [93]:
import numpy as np
k_primes1=[]
def count_Kprimes1(k, start, nd):
    if start == 0:
        start =1
    k_numbers = []
    max_nd_prime = n_primes1(int(nd/4)+1)
    for i in range(nd+1-start):
        if is_k_prime1(start+i,k,max_nd_prime):
            k_numbers.append(start+i)
    return k_numbers
    
def is_k_prime1(num,k,nd):
    global k_primes1
    k_primes1 = []
    devide1(num,nd) 
    if len(k_primes1)==k:
        return True
    
        
def devide1 (num,rng):
    global k_primes1
    for i in rng:
        if num%i == 0 :
            k_primes1.append(i)
            return devide1(num/i,rng) if num/i!= 1 else 1
    
        
def n_primes1 (n):
    k_prime = np.ones((n),dtype = bool)
    for i in range(2,n):
        if k_prime[i] == True:
            for j in range(i*2,n,i):
                k_prime[j]=False
    return k_prime.nonzero()[0][2:].astype(np.int32)

In [94]:
%prun count_Kprimes1(5, 500, 1000)

In [95]:
from typing import List

In [96]:
def checkio(game_result: List[str]) -> str:
    print(game_result)
    o_cord = [(i,j) for i,row in enumerate(game_result) for j,lit in enumerate(row) if lit == 'O']
    x_cord = [(i,j) for i,row in enumerate(game_result) for j,lit in enumerate(row) if lit == 'X']
    
    if is_win_d(o_cord) :#or is_win_v_h(o_cord):
        return "O"
    elif is_win_d(x_cord) :#or is_win_v_h(x_cord):
        return "X"
    else:
        return "D"
    
    
def is_win_v_h (cords):
#     print(cords)
    x = map(lambda x: x[0],cords)
    y = map(lambda x: x[1],cords)
    len_x = [len(list(j)) for _,j in groupby(sorted(x))]
    len_y = [len(list(j)) for _,j in groupby(sorted(y))]
#     print(len_x,len_y)
    if 3 in len_x or 3 in len_y:
        return True
    else:
        return False
    
def is_win_d(cords):
    if (0,2)in cords and (1,1) in cords and (2,0) in cords:
        print(cords)
        return True
    
    cords = ([(i,j) for i,j in cords if i==j])
    if len(cords)==3:
        x = sorted(map(lambda x: x[0],cords))
        y = sorted(map(lambda x: x[1],cords))
        
        if x == y:
            return True   
    return False
    
    

In [97]:
def checkio1(result):
    rows = result
    
    
    cols = map(''.join, zip(*rows))
    
    diags = map(''.join, zip(*[(r[i], r[2 - i]) for i, r in enumerate(rows)]))
    
    lines = rows + list(cols) + list(diags)
    print(lines)

    return 'X' if ('XXX' in lines) else 'O' if ('OOO' in lines) else 'D'

In [98]:
game =[
        "OOX",
        "XXO",
        "OXX"]
checkio1(game)

['OOX', 'XXO', 'OXX', 'OXO', 'OXX', 'XOX', 'OXX', 'XXO']


'D'

In [99]:
[0for globals()['checkio'],checkio.__name__,checkio.__doc__ in[((lambda t,n=range(9),d='.',l=len,s=set:[[*(r[i]for i in n[:9:3]if(l(s(r[i:i+3]))==1)&(r[i]!=d)),*(r[c]for c in n[:3]if(l(s(r[c:9:3]))==1)&(r[c]!=d)),r[0]if(l(s(r[::4]))==1)&(r[0]!=d)else r[4]if(l(s(r[2:7:2]))==1)&(r[4]!=d)else'D'][0]for r in[''.join(t)]][0]),'checkio','Return the result of a game of tic-tac-toe')]]

[0]

In [100]:
def checkio(first, second):
    first = first.split(',')
    second = second.split(',')
    return ', '.join(i for i in first for j in second if i==j)

In [101]:
list_of_funcs = ['print("hello")', 'str(5)', 'print("XD")']
 
for func in list_of_funcs:
    eval(func)

hello
XD


In [102]:
import numpy as np

In [103]:
A = np.array ([2,5,9,8,8,3,2,1,2,1,8])

In [104]:
set_=np.unique(A)
print(set_)
print(np.where(A==A[0],A,A))

[1 2 3 5 8 9]
[2 5 9 8 8 3 2 1 2 1 8]


In [105]:
A = np.array ([2,5,9,8,8,3,2,1,2,1,8])
set_ = np.unique(A)
indeces = [np.where(A==i) for i in set_]
mean_ = [np.mean(i) for i in indeces]
print(mean_)

[8.0, 4.666666666666667, 5.0, 1.0, 5.666666666666667, 2.0]


In [106]:
A = np.array ([2,5,9,8,8,3,2,1,2,1,8])
set_ = np.unique(A)
indeces = map(np.where,[A==i for i in set_])
[np.mean for i in indeces]

[<function numpy.core.fromnumeric.mean>,
 <function numpy.core.fromnumeric.mean>,
 <function numpy.core.fromnumeric.mean>,
 <function numpy.core.fromnumeric.mean>,
 <function numpy.core.fromnumeric.mean>,
 <function numpy.core.fromnumeric.mean>]

In [107]:
import numpy as np
import pandas as pd
A = np.array([2,5,9,8,8,3,2,1,2,1,8])
S = pd.Series(np.arange(len(A)))
G=S.groupby(A)
print(dir(G))
print(S.groupby(A).mean().values)

['__bytes__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '__weakref__', '_accessors', '_add_numeric_operations', '_agg_doc', '_aggregate', '_aggregate_multiple_funcs', '_aggregate_named', '_apply_filter', '_apply_to_column_groupbys', '_apply_whitelist', '_assure_grouper', '_builtin_table', '_concat_objects', '_constructor', '_cumcount_array', '_cython_agg_general', '_cython_table', '_cython_transform', '_def_str', '_deprecations', '_dir_additions', '_dir_deletions', '_get_index', '_get_indices', '_gotitem', '_group_selection', '_index_with_as_index', '_internal_names', '_internal_names_set', '_is_builtin_func', '_is_cython_func', '_iterat

In [108]:
import numpy as np
import pandas as pd
a=[8,5,9,8,8,3,2,1,2,1,2]
b=[9,3,8,5,3,3,8]
c=[1,2,3,4,5,6,7,8,9,]

A = np.array(a)


is_more = np.bincount(A)

if (any(is_more[is_more>1])):
    S = pd.DataFrame({'col 1':A,'col 2':np.arange(len(A))})
    gb_S = S.groupby(S['col 1'])
    largest = gb_S.size().nlargest()
    lrg_val = largest[largest==largest.max()].index.values
    if len(lrg_val)==1:
        print(A[largest.loc[lrg_val[0]]])
    else:
        x=[np.mean(S[S['col 1']==i].index.values) for i in lrg_val]
        print(A_[np.where(np.argmin(x))][0])
    
    
    
else: 
    print(A[0])
    

# [print(j,i) for j,i in gb_S]



# G = S.groupby(A)
# size_ = G.size()
# largest = size_.nlargest()
# closest_labels = largest[largest==largest.max()]
# print (closest_labels.index.values)
# for key,_ in G:
#     print(key)
#     print(G.get_group(key))


NameError: name 'A_' is not defined

In [ ]:
a=[8,5,9,8,8,3,2,1,2,1,2]
b=[9,7,8,3,4,3,8]

A_ = np.array(a)
A = pd.DataFrame({'col 1':A_,'col 2':np.arange(len(A_))})
gb_A = A.groupby(A['col 1'])
largest = gb_A.size().nlargest()
large_val = largest[largest==largest.max()].index.values
print(large_val)
x=[np.mean(A[A['col 1']==i].index.values) for i in large_val]
print(np.argmin(x))
print(A_[np.where(np.argmin(x))])
[print(i) for _,i in gb_A]


In [3]:
def cache(func):
    prev = {}
    def sub(arg):
        if arg in prev:
            return prev[arg]
        res = func(arg)
        prev[arg]= res
        return res
    return sub
    

In [110]:
@cache
def feb(num):
    if num < 2:
        return 1
    return feb(num-1)+feb(num-2)

X = [feb(i) for i in range(16)]
print(X)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]


In [111]:
%timeit X = [feb(i) for i in range(30)]

9.37 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
let = ('a','b','c')
A = (f'{i}{j}{k}' for i in let for j in let for k in let)

In [14]:
print(A.__next__())

aac


In [114]:
import sys

In [2]:
globals()

{'A': ['aaa',
  'aab',
  'aac',
  'aba',
  'abb',
  'abc',
  'aca',
  'acb',
  'acc',
  'baa',
  'bab',
  'bac',
  'bba',
  'bbb',
  'bbc',
  'bca',
  'bcb',
  'bcc',
  'caa',
  'cab',
  'cac',
  'cba',
  'cbb',
  'cbc',
  'cca',
  'ccb',
  'ccc'],
 'In': ['',
  "let = ('a','b','c')\nA = [f'{i}{j}{k}' for i in let for j in let for k in let]",
  'globals()'],
 'Out': {},
 '_': '',
 '__': '',
 '___': '',
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__loader__': None,
 '__name__': '__main__',
 '__package__': None,
 '__spec__': None,
 '_dh': ['C:\\Users\\Сергей\\Phyton'],
 '_i': "let = ('a','b','c')\nA = [f'{i}{j}{k}' for i in let for j in let for k in let]",
 '_i1': "let = ('a','b','c')\nA = [f'{i}{j}{k}' for i in let for j in let for k in let]",
 '_i2': 'globals()',
 '_ih': ['',
  "let = ('a','b','c')\nA = [f'{i}{j}{k}' for i in let for j in let for k in l

In [10]:
locals()

{'In': ['',
  "assert('one','one')",
  "x = 'one'\nassert(x,'one')",
  "x = 'one'\nassert x=='one'",
  "x = 'onfe'\nassert x=='one'",
  "x = 'onfe'\nassert x=='one' , 'tehre is an error'",
  "x = 'onfe'\nassert x=='one' , print('tehre is an error')",
  "x = 'onfe'\nassert x=='one' ",
  "x = 'onfe'\ndir(X)\nassert x=='one' ",
  "x = 'onfe'\ndir(x)\nassert x=='one' ",
  'locals()'],
 'Out': {},
 '_': '',
 '__': '',
 '___': '',
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__loader__': None,
 '__name__': '__main__',
 '__package__': None,
 '__spec__': None,
 '_dh': ['C:\\Users\\Сергей\\Phyton'],
 '_i': "x = 'onfe'\ndir(x)\nassert x=='one' ",
 '_i1': "assert('one','one')",
 '_i10': 'locals()',
 '_i2': "x = 'one'\nassert(x,'one')",
 '_i3': "x = 'one'\nassert x=='one'",
 '_i4': "x = 'onfe'\nassert x=='one'",
 '_i5': "x = 'onfe'\nassert x=='one' , 'tehre is an er

In [14]:
x = 'onfe'
print(dir(__name__))
assert x=='one' 

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


AssertionError: 