In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import linalg
import urllib
from urllib import request

In [2]:
def fmt_items(lines,max_lines=0):
    max_width=max([len(line)for line in lines])
    empty =' '*max_width
    lines = [line.ljust(max_width)for line in lines]
    lines += [empty]*(max_lines - len(lines))
    return lines
def pp (*list):
    lines = [ str(item).split('\n') for item in list]
    max_lines=max([len(item)for  item in lines])
    lines = [fmt_items(item,max_lines=max_lines)for item in lines]
    lines_t= np.array(lines).T
    print('\n'.join([' '.join(line) for  line in lines_t]))

In [15]:
a = np.eye(3, 4, 0,dtype = int)
b = np.eye(3, 4, 1,dtype = int)
c = 2*a + b
print(b)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [7]:
path = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'
file = urllib.request.urlopen(path)

In [8]:
X = np.loadtxt(file,delimiter =',',skiprows=1)

In [9]:
y = X[:,0].copy()

In [10]:
X[:,0] = 1

In [13]:
b = linalg.inv(X.T@X)@X.T@y

In [14]:
b

array([ -3.65580429,  -0.2163955 ,   0.0737306 ,   4.41245058,
       -25.46844878,   7.14320155,  -1.30108768])

### 2.3 Перцептрон: обучение

In [37]:
def predict (example,w):
    return int(np.sum(example*w)>0)

In [38]:
w = np.array([0,0,0])
imput = pd.DataFrame([[1,1,0.3],[1,0.4,0.5],[1,0.7,0.8]])
answer = np.array([1,1,0])

In [39]:
for z in range(1):
    for i,r in imput.iterrows():
        prediction = predict(r,w)
        if prediction != answer[i]:
            if prediction == 0:
                w = w+r
            else:
                w = w-r
        pp(w,prediction,answer[i])
            
print('loop stoped')

    

0    1.0                0 1
1    1.0                   
2    0.3                   
Name: 0, dtype: float64    
0    1.0                1 1
1    1.0                   
2    0.3                   
Name: 0, dtype: float64    
0    0.0       1 0
1    0.3          
2   -0.5          
dtype: float64    
loop stoped


In [36]:
import numpy

examples = numpy.array([
    [1, 1, 0.3],
    [1, 0.4, 0.5],
    [1, 0.7, 0.8]
])
target = [1, 1, 0]
perfect = 0

def predict(x, weights):
    print(x,weights,x @ weights,int((x @ weights) > 0))
    return int((x @ weights) > 0)


w = numpy.array([0, 0, 0])
for re in range(1):
    perfect = 1
    for idx, e in enumerate(examples):
        prediction = predict(e, w)
        
        if prediction == target[idx]:
            continue
        perfect = 0
        if prediction == 0:
            w = w + e
        if prediction == 1:
            w = w - e
        print(prediction,w,e,'\n\n')
print(weights)

[1.  1.  0.3] [0 0 0] 0.0 0
0 [1.  1.  0.3] [1.  1.  0.3] 


[1.  0.4 0.5] [1.  1.  0.3] 1.5499999999999998 1
[1.  0.7 0.8] [1.  1.  0.3] 1.94 1
1 [ 0.   0.3 -0.5] [1.  0.7 0.8] 


[ 0.   0.3 -0.5]


In [4]:
from math import exp
#Функция гиперболического тангенса
def tanh(x):
    return ((exp(x)-exp(x*-1))/(exp(x)+exp(x*-1)))

#Сигмоидальная функция
def sigm(x):
    return 1/(1+(exp(x*-1)))

#Производная гиперболического тангенса
def dtanh(x):
    return ( (1-exp(x-2))**2    *    (-(exp(x-2)+1))**2 ) +1

#Производная сигмоидальной функции
def dsigm(x):
    return ( exp(-x)/(exp(-x)+1)**2 )


#Принт вариантов ответов по почереди подбирая Х

x=12

#1. производная tanh в точке 0 и производная σ в точке 0
print (f'd tanh({x})={dtanh(x)}\nd sigm({x})={dsigm(x)}')

#2. tanh(−x)=1−tanh(x) для любого x
print (f'\ntanh(-x)={tanh(-x)}')
print ('1−tanh(x)=',(1-tanh(x)))

#3 σ(−x)=−σ(x) для любого x (сигмоидальная функция нечётна)
print (f'\nsigm(-x)={sigm(-x)}\n−sigm(x)={-sigm(x)}')

#4. σ(−x)=1−σ(x) для любого x
print (f'\nsigm(-x)={sigm(-x)}\n1-sigm(x)={1-sigm(x)}')

#5 tanh(−x)=−tanh(x) для любого x (гиперболический тангенс нечётен)
print (f'\ntanh(-x)={tanh(-x)}\n-tanh(x)={-tanh(x)}')

d tanh(12)=2.3538526586668966e+17
d sigm(12)=6.1441368513331755e-06

tanh(-x)=-0.9999999999244972
1−tanh(x)= 7.550282621338056e-11

sigm(-x)=6.144174602214718e-06
−sigm(x)=-0.9999938558253978

sigm(-x)=6.144174602214718e-06
1-sigm(x)=6.144174602207286e-06

tanh(-x)=-0.9999999999244972
-tanh(x)=-0.9999999999244972
