In [1]:
import numpy as np


In [2]:
def fmt_items(lines,max_lines=0):
    max_width=max([len(line)for line in lines])
    empty =' '*max_width
    lines = [line.ljust(max_width)for line in lines]
    lines += [empty]*(max_lines - len(lines))
    return lines
def pp (*list):
    lines = [ str(item).split('\n') for item in list]
    max_lines=max([len(item)for  item in lines])
    lines = [fmt_items(item,max_lines=max_lines)for item in lines]
    lines_t= np.array(lines).T
    print('\n'.join([' '.join(line) for  line in lines_t]))

In [95]:
def act_max(x):
    return x if x >0 else 0

def act_max_prime(x):
    return np.where(x>=0,1,0)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

def gen_weidgth (x):
    if len(x.shape)>1:
        return np.random.randn(x.shape[1],1)
    else:
        return np.random.randn(x.shape[0],1)
    
def terget_func (right, predicted):
    return (predicted -right) ** 2

def terget_func_prime(right, predicted):
    return (predicted -right)
    
class Neuron:
    def __init__(self, weidgth, activation = sigmoid, activation_deriv = sigmoid_prime):
        self.d_W = 0
        self.acttivation = activation
        self.activation_deriv = activation_deriv
        self.weidgth = weidgth
    def forvard (self, input_):
        pp('input ', input_, ' of shape ',input_.shape,' @ weidght ',
           self.weidgth,' of shepe ',self.weidgth.shape,' = ')
        self.input_ = input_
        self.output = self.input_@self.weidgth
        self.forvard_res = self.acttivation(self.output)
        return self.forvard_res
    def backward (self, error):
       
        back_active = self.activation_deriv(self.output)*error
        pp ('back_active @ weights.T',back_active,' @ ', self.weidgth.T)
        d_input = back_active@self.weidgth.T
        self.d_W = self.input_[:,None]@back_active
        return d_input
        
    


In [96]:
input_ = np.array([0,1,1])


In [97]:
weights_1 = np.array([[0.7],[0.2],[0.7]])
weights_2 = np.array([[0.8],[0.3],[0.6]])
weights_3 = np.array([[0.2],[0.4]])
l1n1 = Neuron(weights_1,act_max,act_max_prime)
l1n2 = Neuron(weights_2,sigmoid,sigmoid_prime)


In [98]:
one_exit = l1n1.forvard(input_)
two_exit = l1n2.forvard(input_)
next_input = np.concatenate((one_exit,two_exit),axis = None)
print('\noutput of first layer   ',next_input)

input  [0 1 1]  of shape  (3,)  @ weidght  [[0.7]   of shepe  (3, 1)  = 
                                            [0.2]                       
                                            [0.7]]                      
input  [0 1 1]  of shape  (3,)  @ weidght  [[0.8]   of shepe  (3, 1)  = 
                                            [0.3]                       
                                            [0.6]]                      

output of first layer    [0.9       0.7109495]


In [99]:
l2n1 = Neuron(weights_3,sigmoid,sigmoid_prime)
print(l2n1.weidgth)
predict = l2n1.forvard(next_input)
print('\noutput of network  ',predict)

[[0.2]
 [0.4]]
input  [0.9       0.7109495]  of shape  (2,)  @ weidght  [[0.2]   of shepe  (2, 1)  = 
                                                          [0.4]]                      

output of network   [0.61405267]


In [100]:
error = terget_func(1,predict)

print('error  ',error)

error   [0.14895534]


In [101]:
last_delta = terget_func_prime(1,predict)

last_delta

array([-0.38594733])

## Back

In [102]:
last_error = l2n1.backward(last_delta)
last_error

back_active @ weights.T [-0.09146642]  @  [[0.2 0.4]]


array([-0.01829328, -0.03658657])

In [103]:
first_errow = l1n1.backward(last_error[0])
second_errow = l1n2.backward(last_error[1])
first_errow,second_errow

back_active @ weights.T [-0.01829328]  @  [[0.7 0.2 0.7]]
back_active @ weights.T [-0.00751855]  @  [[0.8 0.3 0.6]]


(array([-0.0128053 , -0.00365866, -0.0128053 ]),
 array([-0.00601484, -0.00225557, -0.00451113]))

In [104]:
print(l1n1.d_W)
print(l1n2.d_W)

[ 0.         -0.01829328 -0.01829328]
[ 0.         -0.00751855 -0.00751855]


In [105]:
x = np.array([1,0,0])
y = np.array([1,0.3,0.1])

In [106]:
-0.38594733*0.23699199


-0.0914664257718867